# Generated by Django 5.2.9 on 2025-12-02 19:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_project_kanban_board_schoolclass_project_schoolclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='conflictfile',
            name='tag_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='tag_id'),
        ),
        migrations.AddField(
            model_name='mergeconflict',
            name='work_copy',
            field=models.FileField(default=None, upload_to='', validators=[django.core.validators.FileExtensionValidator(['xml', 'XML'])], verbose_name='File'),
            preserve_default=False,
        ),
    ]