# Generated by Django 5.1.7 on 2026-03-08 17:43

from django.db import migrations
from django.conf import settings
import os
import re


def migrate_sync_urls_to_action_namespace(apps, schema_editor):
    """
    Migration nach Endpoint-Änderung:
    Ändere die Postback-URLs in den XML-Dateien von /sync/ zu /action/sync
    """
    SnapFile = apps.get_model('home', 'SnapFile')

    # /sync/PROJECT_ID?ancestor=FILE_ID
    pattern = re.compile(r'(/sync/[a-f0-9\-]+\?ancestor=[0-9]+)', re.IGNORECASE)

    updated_count = 0
    error_count = 0

    for snap_file in SnapFile.objects.all():
        try:
            file_path = os.path.join(settings.MEDIA_ROOT, str(snap_file.file))

            # Check if file exists
            if not os.path.exists(file_path):
                continue

            # Read file content
            with open(file_path, 'r', encoding='utf-8') as f:
                content = f.read()

            if not pattern.search(content):
                continue

            updated_content = pattern.sub(lambda m: m.group(1).replace('/sync/', '/action/sync/'), content)

            # Write updated content back
            with open(file_path, 'w', encoding='utf-8') as f:
                f.write(updated_content)

            updated_count += 1

        except Exception as e:
            error_count += 1
            print(f"Error updating file {snap_file.id}: {e}")

    print(f"Migration complete: {updated_count} files updated, {error_count} errors")


def reverse_migrate_sync_urls(apps, schema_editor):
    SnapFile = apps.get_model('home', 'SnapFile')

    pattern = re.compile(r'(/action/sync/[a-f0-9\-]+\?ancestor=[0-9]+)', re.IGNORECASE)

    reverted_count = 0
    error_count = 0

    for snap_file in SnapFile.objects.all():
        try:
            file_path = os.path.join(settings.MEDIA_ROOT, str(snap_file.file))

            if not os.path.exists(file_path):
                continue

            with open(file_path, 'r', encoding='utf-8') as f:
                content = f.read()

            if not pattern.search(content):
                continue

            updated_content = pattern.sub(lambda m: m.group(1).replace('/action/sync/', '/sync/'), content)

            with open(file_path, 'w', encoding='utf-8') as f:
                f.write(updated_content)

            reverted_count += 1

        except Exception as e:
            error_count += 1
            print(f"Error reverting file {snap_file.id}: {e}")

    print(f"Reverse migration complete: {reverted_count} files reverted, {error_count} errors")


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0035_conflictfile_tag_id_mergeconflict_work_copy'),
    ]

    operations = [
        migrations.RunPython(
            migrate_sync_urls_to_action_namespace,
            reverse_migrate_sync_urls
        ),
    ]
