# Generated by Django 5.1.7 on 2026-03-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_migrate_sync_urls_to_action_namespace'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='created_at'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_tutorial',
            field=models.BooleanField(default=False, verbose_name='is_tutorial'),
        ),
    ]
