# Generated by Django 5.1.7 on 2026-03-19 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_project_created_at_project_is_tutorial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE auth_user ADD COLUMN completed_tutorial boolean NOT NULL DEFAULT 0;",
            reverse_sql="ALTER TABLE auth_user DROP COLUMN completed_tutorial;",
        ),
    ]
